// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	SocialFollowers
	Person
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocialFollowers struct {
	Youtube int32 `protobuf:"varint,1,opt,name=youtube" json:"youtube,omitempty"`
	Twitter int32 `protobuf:"varint,3,opt,name=twitter" json:"twitter,omitempty"`
}

func (m *SocialFollowers) Reset()                    { *m = SocialFollowers{} }
func (m *SocialFollowers) String() string            { return proto.CompactTextString(m) }
func (*SocialFollowers) ProtoMessage()               {}
func (*SocialFollowers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SocialFollowers) GetYoutube() int32 {
	if m != nil {
		return m.Youtube
	}
	return 0
}

func (m *SocialFollowers) GetTwitter() int32 {
	if m != nil {
		return m.Twitter
	}
	return 0
}

type Person struct {
	Name            string           `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Age             int32            `protobuf:"varint,2,opt,name=Age" json:"Age,omitempty"`
	SocialFollowers *SocialFollowers `protobuf:"bytes,3,opt,name=socialFollowers" json:"socialFollowers,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetSocialFollowers() *SocialFollowers {
	if m != nil {
		return m.SocialFollowers
	}
	return nil
}

func init() {
	proto.RegisterType((*SocialFollowers)(nil), "main.SocialFollowers")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72,
	0xe5, 0xe2, 0x0f, 0xce, 0x4f, 0xce, 0x4c, 0xcc, 0x71, 0xcb, 0xcf, 0xc9, 0xc9, 0x2f, 0x4f, 0x2d,
	0x2a, 0x16, 0x92, 0xe0, 0x62, 0xaf, 0xcc, 0x2f, 0x2d, 0x29, 0x4d, 0x4a, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0d, 0x82, 0x71, 0x41, 0x32, 0x25, 0xe5, 0x99, 0x25, 0x25, 0xa9, 0x45, 0x12, 0xcc,
	0x10, 0x19, 0x28, 0x57, 0x29, 0x9f, 0x8b, 0x2d, 0x00, 0x6c, 0xb8, 0x90, 0x10, 0x17, 0x8b, 0x5f,
	0x62, 0x2e, 0x44, 0x2b, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0xec, 0x98, 0x9e, 0x2a, 0xc1,
	0x04, 0xd6, 0x03, 0x62, 0x0a, 0xd9, 0x73, 0xf1, 0x17, 0xa3, 0x5a, 0x0b, 0x36, 0x91, 0xdb, 0x48,
	0x54, 0x0f, 0xe4, 0x2c, 0x3d, 0x34, 0x37, 0x05, 0xa1, 0xab, 0x4e, 0x62, 0x03, 0x7b, 0xc2, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xda, 0x87, 0x96, 0x2d, 0xd4, 0x00, 0x00, 0x00,
}
